name: Build Doxygen documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Doxygen documentation
      uses: mattnotmitt/doxygen-action@v1

    - name: Deploy to GH pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html